show_topbar: false
header:
  settings:
    color_scheme: theme-1
    padding:
      -
        sides:
          - top
        value: 0
        custom: false
footer:
  settings:
    color_scheme: theme-1
    padding:
      -
        sides:
          - top
        value: 0
        custom: false
primary_color: '#f066bd'
primary_tones_bias: 0
primary_saturation: 0
secondary_color: '#9957ea'
secondary_tones_bias: 0
secondary_saturation: 0
tertiary_color: '#e08e00'
tertiary_tones_bias: 0
tertiary_saturation: 0
quaternary_color: '#0aadff'
quaternary_tones_bias: 0
quaternary_saturation: 0
color_schemes:
  - id: R5vSPNyRuaqss7QHSJZzo
    handle: theme-1
    label: 'Theme 1'
    background_color: '#b8478f'
    text_color: '#fbf2f7'
    inner_background_color: '#ce78ab'
    inner_text_color: '#11010a'
    button_one_color: '#fbf2f7'
    button_one_hover_color: '#f066bd'
    button_two_color: '#11010a'
    button_two_hover_color: '#fbf2f7'
    type: color_scheme
    enabled: true
    highlighted_color: '#f066bd'
  - id: 4ZQiYwmldsmw1S9_UpvJJ
    handle: theme-2
    label: 'Theme 2'
    background_color: '#005ea4'
    text_color: '#eff6fb'
    inner_background_color: '#0080c2'
    inner_text_color: '#eff6fb'
    button_one_color: '#00142a'
    button_one_hover_color: '#eff6fb'
    button_two_color: '#eff6fb'
    button_two_hover_color: '#00142a'
    type: color_scheme
    enabled: true
    highlighted_color: '#00142a'
  - id: OVrDLYqcLdWkE58bmYr0O
    handle: theme-3
    label: 'Theme 3'
    background_color: '#000714'
    text_color: '#eff6fb'
    inner_background_color: '#00142a'
    inner_text_color: '#eff6fb'
    button_one_color: '#0aadff'
    button_one_hover_color: '#eff6fb'
    button_two_color: '#eff6fb'
    button_two_hover_color: '#0aadff'
    type: color_scheme
    enabled: true
    highlighted_color: '#0aadff'
  - id: 3Z8hQiqM2Ik1vQMhkx_-C
    handle: theme-4
    label: 'Theme 4'
    background_color: '#011a60'
    type: color_scheme
    enabled: true
    text_color: '#f5f5f5'
    inner_background_color: '#61ebd4'
    inner_text_color: '#171717'
    button_one_color: '#61ebd4'
    button_one_hover_color: '#f5f5f5'
    button_two_color: '#f5f5f5'
    button_two_hover_color: '#61ebd4'
    highlighted_color: '#61ebd4'
  - id: Wgh0DSChkFOovXoGMIEIp
    handle: theme-5
    label: 'Theme 5'
    background_color: '#001554'
    text_color: '#eff6fb'
    inner_background_color: '#61ebd4'
    inner_text_color: '#001554'
    button_one_color: '#001554'
    highlighted_color: '#61ebd4'
    type: color_scheme
    enabled: true
container_width: 75em
fluid_sizes:
  max_viewport: 1200
  unit: vw
  sizes:
    - handle: size-100
      min: 15
      max: 16
      id: default-0
    - handle: size-200
      min: 16
      max: 18
      id: default-1
    - handle: size-300
      min: 18
      max: 22
      id: default-2
    - handle: size-400
      min: 21
      max: 26
      id: default-3
    - handle: size-500
      min: 24
      max: 34
      id: default-4
    - handle: size-600
      min: 31
      max: 44
      id: default-5
    - handle: size-700
      min: 38
      max: 56
      id: default-6
    - handle: size-800
      min: 48
      max: 70
      id: default-7
    - handle: size-900
      min: 60
      max: 86
      id: default-8
    - handle: size-1000
      min: 72
      max: 110
      id: default-9
    - handle: size-1100
      min: 84
      max: 135
      id: default-10
    - handle: size-1200
      min: 90
      max: 150
      id: default-11
  sizes_css:
    - handle: size-100
      value: 'clamp(0.9375rem, 0.9148rem + 0.1136vw, 1rem)'
    - handle: size-200
      value: 'clamp(1rem, 0.9545rem + 0.2273vw, 1.125rem)'
    - handle: size-300
      value: 'clamp(1.125rem, 1.0341rem + 0.4545vw, 1.375rem)'
    - handle: size-400
      value: 'clamp(1.3125rem, 1.1989rem + 0.5682vw, 1.625rem)'
    - handle: size-500
      value: 'clamp(1.5rem, 1.2727rem + 1.1364vw, 2.125rem)'
    - handle: size-600
      value: 'clamp(1.9375rem, 1.642rem + 1.4773vw, 2.75rem)'
    - handle: size-700
      value: 'clamp(2.375rem, 1.9659rem + 2.0455vw, 3.5rem)'
    - handle: size-800
      value: 'clamp(3rem, 2.5rem + 2.5vw, 4.375rem)'
    - handle: size-900
      value: 'clamp(3.75rem, 3.1591rem + 2.9545vw, 5.375rem)'
    - handle: size-1000
      value: 'clamp(4.5rem, 3.6364rem + 4.3182vw, 6.875rem)'
    - handle: size-1100
      value: 'clamp(5.25rem, 4.0909rem + 5.7955vw, 8.4375rem)'
    - handle: size-1200
      value: 'clamp(5.625rem, 4.2614rem + 6.8182vw, 9.375rem)'
adobe_kits:
  - id: eV0P7nLws1fYIEBVEpLOd
    url: 'https://use.typekit.net/evh2spm.css'
font_family:
  base: Inter
  base_font_weight: '400'
  base_wdth: '100'
  headings: Oswald
  headline_font_weight: 700
  heading_wdth: 100
  headings_uppercase: false
line_height: leading-normal
font_scale_preview:
  h1: size-700
  h2: size-600
  h3: size-500
  h4: size-400
  h5: size-300
  h6: size-200
  p: size-100
button_font: '--font-heading'
button_size: '--size-100'
button_weight: '--font-weight-bold'
button_width: '100'
button_radius: var(--radius-sm)
button_uppercase: true
button_preview:
  bg: '#b8478f'
  text: '#fbf2f7'
opacity: 50%
show_blog: false
show_employees: false
show_services: false
show_cases: false
show_events: false
show_products: false
show_testimonials: false
show_reusable_sections: false
